version: "3.7"
services:
  database:
    image: mongo
    volumes: 
      - mongo-volume:/pa11ydata
    restart: always
    networks:
      - universal
  web:
    depends_on:
      - database
    # image: pallespm/pa11y-docker
    build: .
    ports:
      - "80:4000"
    links:
      - database:mongodb
    restart: always
    networks:
      - universal
volumes:
  mongo-volume:
networks:
  universal: