version: "3.7"
services:
  database:
    image: mongo
    volumes: 
      - mongo-volume:/pa11ydata
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - universal
  web:
    depends_on:
      - database
    image: pallespm/pa11y-docker
    ports:
      - "80:4000"
    links:
      - database
    restart: always
    networks:
      - universal
volumes:
  mongo-volume:
networks:
  universal:
    driver: bridge